### ISSUE TITLE
Importing from Google Photos crash

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#585]
- The first time I selected a photo from Google Photos, an alert about image optimization appeared. I clicked “Leave off” then the screen turned black for a while, then white, then back to My Site. It didn’t happen again.
- After selecting a video from Google Photos under slower network, it went back to the story post editor with an empty canvas (no actions enabled) and then crashed after a few seconds. It might be nice to show the download progress dialog like after selecting pictures from Google Photos.

**Comment by mzorz** [comment]
Been able to reproduce - this is not particular to Stories it seems but rather general to how we request external videos be fed in WPAndroid through the use of [`ACTION_GET_CONTENT`](https://developer.android.com/guide/topics/providers/document-provider.html#client) intent.

A couple of crashes found:

```
2020-11-05 16:56:19.871 6519-6519/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 6519
    java.lang.SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/2/mediakey%3A%2Flocal%253Aeaa96a04-1979-474c-81f3-125f8d27c62d/ORIGINAL/NONE/video%2Fmpeg/199873278 from pid=6519, uid=10044 requires the provider be exported, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:809)
        at android.content.ContentResolver.query(ContentResolver.java:759)
        at android.content.ContentResolver.query(ContentResolver.java:717)
        at org.wordpress.android.util.MediaUtils.getFilenameFromURI(MediaUtils.java:173)
        at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:220)
        at org.wordpress.android.util.MediaUtilsWrapper.copyFileToAppStorage(MediaUtilsWrapper.kt:39)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.copyToAppStorage(CopyMediaToAppStorageUseCase.kt:46)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.access$copyToAppStorage(CopyMediaToAppStorageUseCase.kt:15)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase$copyFilesToAppStorageIfNecessary$2.invokeSuspend(CopyMediaToAppStorageUseCase.kt:29)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase$copyFilesToAppStorageIfNecessary$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.copyFilesToAppStorageIfNecessary(CopyMediaToAppStorageUseCase.kt:25)
        at org.wordpress.android.ui.posts.editor.media.AddLocalMediaToPostUseCase.addNewMediaToEditorAsync(AddLocalMediaToPostUseCase.kt:54)
        at org.wordpress.android.ui.stories.media.StoryEditorMedia$addNewMediaItemsToEditorAsync$1.invokeSuspend(StoryEditorMedia.kt:79)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7080)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2020-11-05 16:56:19.877 1352-7140/? W/ActivityManager: crash : org.wordpress.android,0
2020-11-05 16:56:19.879 1352-7140/? W/ActivityManager:   Force finishing activity org.wordpress.android/.ui.stories.StoryComposerActivity
```


and
```
2020-11-05 17:00:09.256 1352-1381/? W/libprocessgroup: kill(-7546, 9) failed: No such process
2020-11-05 17:00:09.298 8253-8301/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/2/mediakey%3A%2Flocal%253Ac22ab6ec-8874-4c5c-bec9-0e1ff260ffcb/ORIGINAL/NONE/video%2Fmpeg/1418135488 from pid=7609, uid=10044 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:645)
        at android.content.ContentProvider.semEnforceReadPermission(ContentProvider.java:564)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:503)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:214)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:739)
```

From my tests, I observed the same black screen and  "no feedback presented"  happens when feeding videos from Google Photos to Gutenberg and Aztec as well, with the difference that in these 2 cases using the same videos didn't end up crashing the app.
The crashes happen after some time, when the URI permissions are revoked.

I have observed the "adding media" progress dialog was not being shown or shown only for multiple media selection and changed that in a work in progress local branch, which gives you feedback but it did finally end up in the SecurtyException being thrown.

Will continue digging and hope to find a workaround soon.
