### ISSUE TITLE
Crash on first use

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#682]
This happened to me yesterday on a Pixel 4a, Android 10, latest WPAndroid at commit https://github.com/wordpress-mobile/WordPress-Android/commit/165c7d159ed3b54de057f60ce58cb42b17d40172, and latest Stories `develop` at  https://github.com/Automattic/stories-android/commit/6573eda399d1030fa9bcaccd7912da9bfd21d70a
 
Steps to reproduce (it only happened to me once but I remember exactly the steps I took)
- install app from scratch
- tap fab, new story
- allow permissions in the picker
- pick 2 or 3 photos
- tap check to confirm and observe crash

```
2021-05-06 09:33:10.803 20616-20616/org.wordpress.android D/WordPress-MAIN: DynamicCardStore: Get dynamic card
2021-05-06 09:33:10.832 20616-20616/org.wordpress.android I/WordPress-STATS: 🔵 Tracked: editor_session_end, Properties: {"has_unsupported_blocks":"0","editor":"wp_stories_creator","content_type":"new","session_id":"9681c3a0-628d-4f99-a4d8-650f29c07b67","post_type":"post","blog_type":"wpcom","editor_has_hw_disabled":"0","outcome":"cancel"}
2021-05-06 09:33:10.843 20616-20616/org.wordpress.android E/WindowManager: android.view.WindowLeaked: Activity org.wordpress.android.ui.stories.StoryComposerActivity has leaked window DecorView@4e4fbc5[StoryComposerActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:736)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:720)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
        at android.app.Dialog.show(Dialog.java:340)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
        at org.wordpress.android.util.WPMediaUtils.advertiseImageOptimization(WPMediaUtils.java:164)
        at org.wordpress.android.ui.stories.StoryComposerActivity.advertiseImageOptimization(StoryComposerActivity.kt:418)
        at org.wordpress.android.ui.stories.media.StoryEditorMedia.advertiseImageOptimisationAndAddMedia(StoryEditorMedia.kt:61)
        at org.wordpress.android.ui.stories.media.StoryEditorMedia.onPhotoPickerMediaChosen(StoryEditorMedia.kt:99)
        at org.wordpress.android.ui.stories.StoryComposerActivity.handleMediaPickerIntentData(StoryComposerActivity.kt:358)
        at org.wordpress.android.ui.stories.StoryComposerActivity.onLoadFromIntent(StoryComposerActivity.kt:273)
        at com.wordpress.stories.compose.ComposeLoopFrameActivity$onCreate$5.onBackgroundSurfaceManagerReady(ComposeLoopFrameActivity.kt:486)
        at com.automattic.photoeditor.state.BackgroundSurfaceManager$onCreate$1$1.onSurfaceTextureAvailable(BackgroundSurfaceManager.kt:94)
        at com.automattic.photoeditor.views.PhotoEditorView$mainSurfaceTextureListener$1.onSurfaceTextureAvailable(PhotoEditorView.kt:60)
        at android.view.TextureView.getTextureLayer(TextureView.java:402)
        at android.view.TextureView.draw(TextureView.java:351)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22353)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.updateDisplayListIfDirty(View.java:21217)
        at android.view.View.draw(View.java:22081)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
        at android.view.View.draw(View.java:22353)
        at com.android.internal.policy.DecorView.draw(DecorView.java:806)
        at android.view.View.updateDisplayListIfDirty(View.java:21226)
2021-05-06 09:33:10.843 20616-20616/org.wordpress.android E/WindowManager:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-05-06 09:33:10.867 1685-6067/? W/WindowManager: Failed looking up window session=Session{13d49c8 20616:u0a10321} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5435 com.android.server.wm.WindowManagerService.removeWindow:1898 com.android.server.wm.Session.remove:193 
2021-05-06 09:33:11.030 20616-20616/org.wordpress.android D/WordPress-API: Dispatching action: AccountAction-FETCHED_ACCOUNT
```

**Comment by aforcier** [comment]
I'm getting a similar looking crash in the same place, though for me it happens on every launch of the app, doesn't need to be a clean reinstall:

```
2021-05-08 08:28:44.252 16737-16737/org.wordpress.android.beta I/WordPress-STATS: 🔵 Tracked: editor_session_end, Properties: {"has_unsupported_blocks":"0","editor":"wp_stories_creator","content_type":"new","session_id":"20b5790a-a656-42f4-b867-42a3ebe83e58","post_type":"post","blog_type":"wpcom","editor_has_hw_disabled":"0","outcome":"cancel"}
2021-05-08 08:28:44.258 16737-16737/org.wordpress.android.beta E/WindowManager: android.view.WindowLeaked: Activity org.wordpress.android.ui.stories.StoryComposerActivity has leaked window DecorView@d1949ec[StoryComposerActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:736)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:720)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
        at android.app.Dialog.show(Dialog.java:340)
        at org.wordpress.android.ui.posts.ProgressDialogHelper.updateProgressDialogState(ProgressDialogHelper.kt:41)
        at org.wordpress.android.ui.stories.StoryComposerActivity.updateAddingMediaToStoryComposerProgressDialogState(StoryComposerActivity.kt:436)
        at org.wordpress.android.ui.stories.StoryComposerActivity.access$updateAddingMediaToStoryComposerProgressDialogState(StoryComposerActivity.kt:88)
        at org.wordpress.android.ui.stories.StoryComposerActivity$setupStoryEditorMediaObserver$1.onChanged(StoryComposerActivity.kt:386)
        at org.wordpress.android.ui.stories.StoryComposerActivity$setupStoryEditorMediaObserver$1.onChanged(StoryComposerActivity.kt:88)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at org.wordpress.android.ui.stories.media.StoryEditorMedia$addNewMediaItemsToEditorAsync$1.invokeSuspend(StoryEditorMedia.kt:74)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

It happens at the last commit of https://github.com/wordpress-mobile/WordPress-Android/pull/14588, so WPAndroid https://github.com/wordpress-mobile/WordPress-Android/pull/14588/commits/8bc6e92f5a75c2b1978153ce3a7127babef5f5fc and stories 71a33ba.
